#ifndef SWF_ENUM__
#define SWF_ENUM__

namespace SWF
{
	enum Tag
	{
		END = 0,
		SHOWFRAME = 1,
		DEFINESHAPE = 2,
		
		PLACEOBJECT = 4,
		REMOVEOBJECT = 5,
		DEFINEBITS = 6,
		DEFINEBUTTON = 7,
		JPEGTABLES = 8,
		SETBACKGROUNDCOLOR = 9,
		DEFINEFONT = 10,
		DEFINETEXT = 11,
		DOACTION = 12,
		DEFINEFONTINFO = 13,
		DEFINESOUND = 14,
		STARTSOUND = 15,
		STOPSOUND = 16,
		DEFINEBUTTONSOUND = 17,
		SOUNDSTREAMHEAD = 18,
		SOUNDSTREAMBLOCK = 19,
		DEFINELOSSLESS = 20,
		DEFINEBITSJPEG2 = 21,
		DEFINESHAPE2 = 22,
		DEFINEBUTTONCXFORM = 23,
		PROTECT = 24,

		PLACEOBJECT2 = 26,

		REMOVEOBJECT2 = 28,
		
		DEFINESHAPE3 = 32,
		DEFINETEXT2 = 33,
		DEFINEBUTTON2 = 34,
		DEFINEBITSJPEG3 = 35,
		DEFINELOSSLESS2 = 36,
		DEFINEEDITTEXT = 37,

		DEFINESPRITE = 39,

		FRAMELABEL = 43,

		SOUNDSTREAMHEAD2 = 45,
		DEFINEMORPHSHAPE = 46,

		DEFINEFONT2 = 48,

		EXPORTASSETS = 56,
		IMPORTASSETS = 57,
		ENABLEDEBUGGER = 58,
		INITACTION = 59,
		DEFINEVIDEOSTREAM = 60,
		VIDEOFRAME = 61,
		DEFINEFONTINFO2 = 62,

		ENABLEDEBUGGER2 = 64,
		SCRIPTLIMITS = 65,
		SETTABINDEX = 66,

		FILEATTRIBUTES = 69,
		PLACEOBJECT3 = 70,
		IMPORTASSETS2 = 71,

		DEFINEALIGNZONES = 73,
		CSMTEXTSETTINGS = 74,
		DEFINEFONT3 = 75,
		SYMBOLCLASS = 76,
		METADATA = 77,
		DEFINESCALINGGRID = 78,

		DOABCDEFINE = 82,
		DEFINESHAPE4 = 83,
		DEFINEMORPHSHAPE2 = 84,

		DEFINESCENEANDFRAMELABELDATA = 86,
		DEFINEBINARYDATA = 87,
		DEFINEFONTNAME = 88,
		STARTSOUND2 = 89,
	};
}

#endif